### ISSUE TITLE
Executable doesn't work nav_node

### ISSUE THREAD

**Issue by Bandamo** [7Robot/nav_node#2]
Après compilation sur colcon, l'executable "nav_node" n'est pas accessible depuis la commande "ros2 run nav_node nav_node".
Il faut vérifier si cela fonctionne sur Raspberry (dans ce cas ce sera une erreur de ma VM) sinon il faudra éditer le CMakeLists.txt et le package.xml

**Comment by MartH76** [comment]
vérifié et fonctionne sur ma raspi
